version: '3.8'

services:
  web:
    build: .
    ports:
      - "9987:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    depends_on:
      - db

  db:
    image: nouchka/sqlite3
    volumes:
      - sqlite_data:/root/db

volumes:
  sqlite_data:
